name: Node.js CI with Docker

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Node.js App
        run: npm run build

      - name: Extract Version from package.json
        id: version
        run: echo ::set-output name=VERSION::$(node -p "require('./package.json').version")

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      - name: Run Docker Buildx (main branch only)
        if: github.ref == 'refs/heads/ci'
        run: |
          docker buildx build -t alexandrevsd/network-scanner-api:latest -t alexandrevsd/network-scanner-api:${{ steps.version.outputs.VERSION }} . --push
